name: scan_n_select
description: ScanNSelect is an application which will help you store your wardrobe digitally and suggest you clothes for travel according to weather of Destination.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  animated_text_kit: ^1.3.0
  qr_flutter: ^3.2.0
  palette_generator: ^0.2.0
  image_picker: ^0.6.6+5
  printing: ^4.1.0
  pdf: ^2.0.0
  path_provider: ^1.6.5
  firebase_core: ^0.3.4
  firebase_auth: ^0.8.4+4
  firebase_storage: ^2.1.1+1
  cloud_firestore: ^0.9.13+1
  modal_progress_hud: ^0.1.3
  rflutter_alert: ^1.0.3
  qrscan: ^0.2.17
  geolocator: ^5.1.5
  flutter_google_places: ^0.2.8
  network_image_to_byte: ^0.0.1
  geocoder: ^0.2.1
  google_maps_flutter: ^0.5.27
  flutter_swiper: ^1.1.6
  location: ^3.0.0
  audioplayers: ^0.13.0
  file_picker: ^1.7.0
  advance_pdf_viewer: ^1.2.2
  widget_circular_animator: ^0.1.5+1
  flutter_image_compress: ^0.7.0
  intl: ^0.16.1
  http: ^0.12.2
  webview_flutter: 1.0.0
  flutter_local_notifications: 4.0.0
  mime_type: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/Weather/
